# Generated by Django 5.2.6 on 2025-09-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_views',
            new_name='product_views',
        ),
        migrations.AddField(
            model_name='news',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('sepakbola', 'Sepakbola'), ('basket', 'Basket'), ('voli', 'Voli'), ('padel', 'Padel'), ('lari', 'Lari'), ('bulutangkis', 'Bulutangkis')], default='update', max_length=20),
        ),
    ]
